# docker-compose.yml para orquestrar ambos os containers
# Salve este arquivo como docker-compose.yml na raiz do projeto

# docker-compose.yml
version: '3.9'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile_mariadb
    container_name: mariadb_container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: school_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile_flask
    container_name: flask_app_container
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DB_HOST: mariadb
      FLASK_DB_USER: flask_user
      FLASK_DB_PASSWORD: flask_password
      FLASK_DB_NAME: school_db

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - mysqld_exporter

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter_container
    environment:
      DATA_SOURCE_NAME: "flask_user:flask_password@(mariadb:3306)/school_db"
    depends_on:
      - mariadb

volumes:
  db_data:
  grafana_data:

networks:
  default:
    name: monitoring_network
